### PR TITLE
Changed directory structure, added '/' endpoint, disabled posterator

### PR DESCRIPTION
**Pull request by sakekasi**

### CODE REVIEW

**Comment by nfischer** [comment]
Instructions for running? I got the web page hosted at http://localhost:5000/, but it's a blank timeline (no weeks).

**Comment by sakekasi** [comment]
care to open up the console and tell me what errors it may be outputting?

**Comment by nfischer** [comment]
Failed to load resource css/style.css
Failed to load resource js/index.js

**Comment by nfischer** [comment]
If the failed to load resource errors go away, and documentation in README gets updated, I think this is safe to merge.

**Pull request merged**
