### PR TITLE
Frontend testing

### PR DESCRIPTION
**Pull request by drudiger**
Not sure if this is the preferred method, or if I should try to merge from master first or something, but here goes. This has the two store tests in it, so the evaluation team can at least run something.

### CODE REVIEW

**Comment by nfischer** [comment]
Can you successfully run `npm i`? I tried to do this (in order to get `gulp build_browser` to work, and `npm i` failed.

**Comment by drudiger** [comment]
I've had problems pretty much every time I've tried to do anything, and had to fix them before continuing. What was the error? If it's EACCES, run "sudo chown -R $(whoami) ~/.npm"

**Comment by nfischer** [comment]
I changed to `backend/frontend/` and ran `npm i`. This is the error message I got:

```
$ npm i # ran this command
npm WARN package.json frontend@1.0.0 No README data
npm WARN package.json babel-plugin-syntax-flow@6.1.18 No description
npm WARN unmet dependency /home/nate/programming/dashboard/backend/frontend/node_modules/react-bootstrap requires babel-runtime@'^5.8.25' but will load
npm WARN unmet dependency /home/nate/programming/dashboard/backend/frontend/node_modules/babel-runtime,
npm WARN unmet dependency which is version 6.2.0
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.27.3 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.3 wants react@^0.14.3

npm ERR! System Linux 4.2.0-18-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/nate/programming/dashboard/backend/frontend
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nate/programming/dashboard/backend/frontend/npm-debug.log
npm ERR! not ok code 0
```

However, `gulp build_browser` seems to work (I think I was in the wrong directory before). Are these errors something I should be concerned about?

**Comment by sakekasi** [comment]
2 main comments.
1. run `git rebase master` so that your branch is up to date with the curent master
2. nate's using a really old version of node. current version is 5.0 (ubuntu is being stupid and installing an old version of node and npm). I would try running `npm i` after upgrading node and npm

**Pull request merged**
